discovery:
 image: discovery
 ports:
   - "8761:8761"
accountsservice:
  image: accountsservice
  ports:
    - "2222:2222"
  links:
    - discovery
apigateway:
  image: apigateway
  ports:
    - "3333:3333"
  links:
    - discovery
